import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "BatBat-Admin",
  description: "Generated by BatMedia",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="w-full">{children}</body>
    </html>
  );
}
